### ISSUE TITLE
TypeDB Cluster client is noisy in Python

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb-driver-python#220]
## Problem to Solve

The Cluster code in client-java makes heavy use of `LOG.debug` to print out debugging statements. But in client-python, we don't currently use Logback (or similar) - we simply use `print`.

This means that the Cluster client prints out a fair bit of noise (for example, it outputs to stdout every time we open a session)

## Proposed Solution

We should see if there's a good logging library for Python and use it if so. If not, we should simply delete the debugging statements, at least once we're satisfied with the stability of the system.

**Comment by alexjpwalker** [comment]
As we move to delegating method calls to Rust via FFI, we should consider how Rust logging interacts with Python logging.

**Comment by flyingsilverfin** [comment]
This is solved as of 2.24.x
