### ISSUE TITLE
Implement direct sub (sub!) in client Concept API

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb-driver-python#279]
We are missing getting the direct subtype in the python client concept API. 
It is available on the backend Concept API and the , but not in the python (and nodes) concept APIs

**Comment by alexjpwalker** [comment]
This issue will be fixed by making all clients delegate their work to the Rust Client.

**Comment by flyingsilverfin** [comment]
This has been addressed by wrapping the python driver around the rust driver in https://github.com/vaticle/typedb-driver-java/pull/438
