### ISSUE TITLE
Client exposes too many methods to create Options object

### ISSUE THREAD

**Issue by james-whiteside** [vaticle/typedb-driver-python#294]
## Description

Client Python currently exposes too many methods to create a `TypeDBOptions` object. It can be instantiated through any of the following:

`TypeDBOptions().core()`
`TypeDBOptions().cluster()`
`TypeDBClusterOptions().core()`
`TypeDBClusterOptons().cluster()`

This creates ambiguity in which methods to use, not to mention including nonsensical options.

## Environment

1. TypeDB client-python version: 2.17.0
2. Python version: 3.9.16

## Expected Output

Only two options should be exposed, probably among the following:

`TypeDBOptions().core()`
`TypeDBOptions().cluster()`

or

`TypeDBOptions()`
`TypeDBClusterOptions()`

or

`TypeDBOptions().core()`
`TypeDBClusterOptions().cluster()`

## Actual Output

Client Python exposes the four options listed above.

**Comment by flyingsilverfin** [comment]
Fixed in the refactor that occurred in #304
